version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
