# Site settings
title: Tableau Server Client Library (Python)
email: github@tableau.com
description: Simplify interactions with the Tableau Server REST API.
baseurl: "/server-client-python"
permalinks: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

